/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
using Workforce.Model;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing BranchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BranchApiTests : IDisposable
    {
        private BranchApi instance;

        public BranchApiTests()
        {
            instance = new BranchApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BranchApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BranchApi
            //Assert.IsType(typeof(BranchApi), instance, "instance is a BranchApi");
        }

        
        /// <summary>
        /// Test BranchById
        /// </summary>
        [Fact]
        public void BranchByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.BranchById(id);
            //Assert.IsType<Branch> (response, "response is Branch");
        }
        
        /// <summary>
        /// Test V1BranchGet
        /// </summary>
        [Fact]
        public void V1BranchGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1BranchGet();
            //Assert.IsType<List<Branch>> (response, "response is List<Branch>");
        }
        
        /// <summary>
        /// Test V1BranchPost
        /// </summary>
        [Fact]
        public void V1BranchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Branch branch = null;
            //instance.V1BranchPost(branch);
            
        }
        
    }

}
