/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
// uncomment below to import models
//using Workforce.Model;

namespace Workforce.Test.Api
{
    /// <summary>
    ///  Class for testing CountryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CountryApiTests : IDisposable
    {
        private CountryApi instance;

        public CountryApiTests()
        {
            instance = new CountryApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountryApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CountryApi
            //Assert.IsType<CountryApi>(instance);
        }

        /// <summary>
        /// Test CreateOrUpdateCountry
        /// </summary>
        [Fact]
        public void CreateOrUpdateCountryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Country country = null;
            //instance.CreateOrUpdateCountry(country);
        }

        /// <summary>
        /// Test DeleteCountry
        /// </summary>
        [Fact]
        public void DeleteCountryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.DeleteCountry(id);
        }

        /// <summary>
        /// Test GetCountries
        /// </summary>
        [Fact]
        public void GetCountriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetCountries();
            //Assert.IsType<List<Country>>(response);
        }

        /// <summary>
        /// Test GetCountriesWithRegions
        /// </summary>
        [Fact]
        public void GetCountriesWithRegionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetCountriesWithRegions();
            //Assert.IsType<List<Country>>(response);
        }

        /// <summary>
        /// Test GetCountry
        /// </summary>
        [Fact]
        public void GetCountryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetCountry(id);
            //Assert.IsType<Country>(response);
        }
    }
}
