/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
using Workforce.Model;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing CountryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CountryApiTests : IDisposable
    {
        private CountryApi instance;

        public CountryApiTests()
        {
            instance = new CountryApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CountryApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CountryApi
            //Assert.IsType(typeof(CountryApi), instance, "instance is a CountryApi");
        }

        
        /// <summary>
        /// Test CountryById
        /// </summary>
        [Fact]
        public void CountryByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.CountryById(id);
            //Assert.IsType<Country> (response, "response is Country");
        }
        
        /// <summary>
        /// Test V1CountryFullGet
        /// </summary>
        [Fact]
        public void V1CountryFullGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1CountryFullGet();
            //Assert.IsType<List<Country>> (response, "response is List<Country>");
        }
        
        /// <summary>
        /// Test V1CountryGet
        /// </summary>
        [Fact]
        public void V1CountryGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1CountryGet();
            //Assert.IsType<List<Country>> (response, "response is List<Country>");
        }
        
        /// <summary>
        /// Test V1CountryPost
        /// </summary>
        [Fact]
        public void V1CountryPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Country country = null;
            //instance.V1CountryPost(country);
            
        }
        
    }

}
