/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
// uncomment below to import models
//using Workforce.Model;

namespace Workforce.Test.Api
{
    /// <summary>
    ///  Class for testing DepartmentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DepartmentApiTests : IDisposable
    {
        private DepartmentApi instance;

        public DepartmentApiTests()
        {
            instance = new DepartmentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DepartmentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DepartmentApi
            //Assert.IsType<DepartmentApi>(instance);
        }

        /// <summary>
        /// Test CreateOrUpdateDepartment
        /// </summary>
        [Fact]
        public void CreateOrUpdateDepartmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Department department = null;
            //instance.CreateOrUpdateDepartment(department);
        }

        /// <summary>
        /// Test DeleteDepartment
        /// </summary>
        [Fact]
        public void DeleteDepartmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.DeleteDepartment(id);
        }

        /// <summary>
        /// Test GetDepartment
        /// </summary>
        [Fact]
        public void GetDepartmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetDepartment(id);
            //Assert.IsType<Department>(response);
        }

        /// <summary>
        /// Test GetDepartments
        /// </summary>
        [Fact]
        public void GetDepartmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDepartments();
            //Assert.IsType<List<Department>>(response);
        }
    }
}
