/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
// uncomment below to import models
//using Workforce.Model;

namespace Workforce.Test.Api
{
    /// <summary>
    ///  Class for testing EmployeeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmployeeApiTests : IDisposable
    {
        private EmployeeApi instance;

        public EmployeeApiTests()
        {
            instance = new EmployeeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmployeeApi
            //Assert.IsType<EmployeeApi>(instance);
        }

        /// <summary>
        /// Test CreateOrUpdateEmployee
        /// </summary>
        [Fact]
        public void CreateOrUpdateEmployeeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Employee employee = null;
            //var response = instance.CreateOrUpdateEmployee(employee);
            //Assert.IsType<Employee>(response);
        }

        /// <summary>
        /// Test DeleteEmployee
        /// </summary>
        [Fact]
        public void DeleteEmployeeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.DeleteEmployee(id);
        }

        /// <summary>
        /// Test GetEmployee
        /// </summary>
        [Fact]
        public void GetEmployeeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetEmployee(id);
            //Assert.IsType<Employee>(response);
        }

        /// <summary>
        /// Test GetEmployees
        /// </summary>
        [Fact]
        public void GetEmployeesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetEmployees();
            //Assert.IsType<List<Employee>>(response);
        }

        /// <summary>
        /// Test SearchEmployees
        /// </summary>
        [Fact]
        public void SearchEmployeesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string firstName = null;
            //string lastName = null;
            //var response = instance.SearchEmployees(firstName, lastName);
            //Assert.IsType<List<Employee>>(response);
        }
    }
}
