/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
using Workforce.Model;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing EmploymentTypeApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmploymentTypeApiTests : IDisposable
    {
        private EmploymentTypeApi instance;

        public EmploymentTypeApiTests()
        {
            instance = new EmploymentTypeApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmploymentTypeApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EmploymentTypeApi
            //Assert.IsType(typeof(EmploymentTypeApi), instance, "instance is a EmploymentTypeApi");
        }

        
        /// <summary>
        /// Test EmploymentTypeById
        /// </summary>
        [Fact]
        public void EmploymentTypeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.EmploymentTypeById(id);
            //Assert.IsType<EmploymentType> (response, "response is EmploymentType");
        }
        
        /// <summary>
        /// Test V1EmploymentTypeGet
        /// </summary>
        [Fact]
        public void V1EmploymentTypeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1EmploymentTypeGet();
            //Assert.IsType<List<EmploymentType>> (response, "response is List<EmploymentType>");
        }
        
        /// <summary>
        /// Test V1EmploymentTypePost
        /// </summary>
        [Fact]
        public void V1EmploymentTypePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EmploymentType employmentType = null;
            //instance.V1EmploymentTypePost(employmentType);
            
        }
        
    }

}
