/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
using Workforce.Model;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing LocationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LocationApiTests : IDisposable
    {
        private LocationApi instance;

        public LocationApiTests()
        {
            instance = new LocationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LocationApi
            //Assert.IsType(typeof(LocationApi), instance, "instance is a LocationApi");
        }

        
        /// <summary>
        /// Test LocationById
        /// </summary>
        [Fact]
        public void LocationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.LocationById(id);
            //Assert.IsType<Location> (response, "response is Location");
        }
        
        /// <summary>
        /// Test V1LocationGet
        /// </summary>
        [Fact]
        public void V1LocationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1LocationGet();
            //Assert.IsType<List<EmploymentType>> (response, "response is List<EmploymentType>");
        }
        
        /// <summary>
        /// Test V1LocationPost
        /// </summary>
        [Fact]
        public void V1LocationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Location location = null;
            //instance.V1LocationPost(location);
            
        }
        
    }

}
