/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
using Workforce.Model;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing NationalityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NationalityApiTests : IDisposable
    {
        private NationalityApi instance;

        public NationalityApiTests()
        {
            instance = new NationalityApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NationalityApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NationalityApi
            //Assert.IsType(typeof(NationalityApi), instance, "instance is a NationalityApi");
        }

        
        /// <summary>
        /// Test NationalityById
        /// </summary>
        [Fact]
        public void NationalityByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.NationalityById(id);
            //Assert.IsType<Nationality> (response, "response is Nationality");
        }
        
        /// <summary>
        /// Test V1NationalityGet
        /// </summary>
        [Fact]
        public void V1NationalityGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.V1NationalityGet();
            //Assert.IsType<List<Nationality>> (response, "response is List<Nationality>");
        }
        
        /// <summary>
        /// Test V1NationalityPost
        /// </summary>
        [Fact]
        public void V1NationalityPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Nationality nationality = null;
            //instance.V1NationalityPost(nationality);
            
        }
        
    }

}
