/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Workforce.Client;
using Workforce.Api;
// uncomment below to import models
//using Workforce.Model;

namespace Workforce.Test.Api
{
    /// <summary>
    ///  Class for testing NationalityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NationalityApiTests : IDisposable
    {
        private NationalityApi instance;

        public NationalityApiTests()
        {
            instance = new NationalityApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NationalityApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NationalityApi
            //Assert.IsType<NationalityApi>(instance);
        }

        /// <summary>
        /// Test CreateOrUpdateNationality
        /// </summary>
        [Fact]
        public void CreateOrUpdateNationalityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Nationality nationality = null;
            //instance.CreateOrUpdateNationality(nationality);
        }

        /// <summary>
        /// Test DeleteNationality
        /// </summary>
        [Fact]
        public void DeleteNationalityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? id = null;
            //instance.DeleteNationality(id);
        }

        /// <summary>
        /// Test GetNationalities
        /// </summary>
        [Fact]
        public void GetNationalitiesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetNationalities();
            //Assert.IsType<List<Nationality>>(response);
        }

        /// <summary>
        /// Test GetNationality
        /// </summary>
        [Fact]
        public void GetNationalityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetNationality(id);
            //Assert.IsType<Nationality>(response);
        }
    }
}
