/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Workforce.Client.OpenAPIDateConverter;

namespace Workforce.Model
{
    /// <summary>
    /// Nationality
    /// </summary>
    [DataContract(Name = "Nationality")]
    public partial class Nationality : IEquatable<Nationality>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Nationality" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Nationality() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Nationality" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="nationalityName">nationalityName (required).</param>
        public Nationality(Guid id = default(Guid), string nationalityName = default(string))
        {
            // to ensure "nationalityName" is required (not null)
            this.NationalityName = nationalityName ?? throw new ArgumentNullException("nationalityName is a required property for Nationality and cannot be null");
            this.Id = id;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets NationalityName
        /// </summary>
        [DataMember(Name = "nationalityName", IsRequired = true, EmitDefaultValue = false)]
        public string NationalityName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Nationality {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NationalityName: ").Append(NationalityName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Nationality);
        }

        /// <summary>
        /// Returns true if Nationality instances are equal
        /// </summary>
        /// <param name="input">Instance of Nationality to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Nationality input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.NationalityName == input.NationalityName ||
                    (this.NationalityName != null &&
                    this.NationalityName.Equals(input.NationalityName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.NationalityName != null)
                    hashCode = hashCode * 59 + this.NationalityName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NationalityName (string) maxLength
            if(this.NationalityName != null && this.NationalityName.Length > 200)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NationalityName, length must be less than 200.", new [] { "NationalityName" });
            }

            yield break;
        }
    }

}
