/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing AbsenceSearchCriteria
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AbsenceSearchCriteriaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AbsenceSearchCriteria
        //private AbsenceSearchCriteria instance;

        public AbsenceSearchCriteriaTests()
        {
            // TODO uncomment below to create an instance of AbsenceSearchCriteria
            //instance = new AbsenceSearchCriteria();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AbsenceSearchCriteria
        /// </summary>
        [Fact]
        public void AbsenceSearchCriteriaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AbsenceSearchCriteria
            //Assert.IsInstanceOfType<AbsenceSearchCriteria> (instance, "variable 'instance' is a AbsenceSearchCriteria");
        }


        /// <summary>
        /// Test the property 'EmployeeId'
        /// </summary>
        [Fact]
        public void EmployeeIdTest()
        {
            // TODO unit test for the property 'EmployeeId'
        }
        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }
        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
