/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test.Model
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        public AddressTests()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Fact]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" Address
            //Assert.IsType<Address>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ValidFrom'
        /// </summary>
        [Fact]
        public void ValidFromTest()
        {
            // TODO unit test for the property 'ValidFrom'
        }
        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }
        /// <summary>
        /// Test the property 'AddressLine2'
        /// </summary>
        [Fact]
        public void AddressLine2Test()
        {
            // TODO unit test for the property 'AddressLine2'
        }
        /// <summary>
        /// Test the property 'TownCity'
        /// </summary>
        [Fact]
        public void TownCityTest()
        {
            // TODO unit test for the property 'TownCity'
        }
        /// <summary>
        /// Test the property 'County'
        /// </summary>
        [Fact]
        public void CountyTest()
        {
            // TODO unit test for the property 'County'
        }
        /// <summary>
        /// Test the property 'PostCode'
        /// </summary>
        [Fact]
        public void PostCodeTest()
        {
            // TODO unit test for the property 'PostCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
