/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test.Model
{
    /// <summary>
    ///  Class for testing Communication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommunicationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Communication
        //private Communication instance;

        public CommunicationTests()
        {
            // TODO uncomment below to create an instance of Communication
            //instance = new Communication();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Communication
        /// </summary>
        [Fact]
        public void CommunicationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Communication
            //Assert.IsType<Communication>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CommunicationType'
        /// </summary>
        [Fact]
        public void CommunicationTypeTest()
        {
            // TODO unit test for the property 'CommunicationType'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

    }

}
