/* 
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test
{
    /// <summary>
    ///  Class for testing EmployeeCommunicationXref
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmployeeCommunicationXrefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmployeeCommunicationXref
        //private EmployeeCommunicationXref instance;

        public EmployeeCommunicationXrefTests()
        {
            // TODO uncomment below to create an instance of EmployeeCommunicationXref
            //instance = new EmployeeCommunicationXref();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmployeeCommunicationXref
        /// </summary>
        [Fact]
        public void EmployeeCommunicationXrefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EmployeeCommunicationXref
            //Assert.IsInstanceOfType<EmployeeCommunicationXref> (instance, "variable 'instance' is a EmployeeCommunicationXref");
        }


        /// <summary>
        /// Test the property 'CommunicationId'
        /// </summary>
        [Fact]
        public void CommunicationIdTest()
        {
            // TODO unit test for the property 'CommunicationId'
        }
        /// <summary>
        /// Test the property 'Communication'
        /// </summary>
        [Fact]
        public void CommunicationTest()
        {
            // TODO unit test for the property 'Communication'
        }
        /// <summary>
        /// Test the property 'LinkType'
        /// </summary>
        [Fact]
        public void LinkTypeTest()
        {
            // TODO unit test for the property 'LinkType'
        }

    }

}
