/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test.Model
{
    /// <summary>
    ///  Class for testing EmploymentType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmploymentTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmploymentType
        //private EmploymentType instance;

        public EmploymentTypeTests()
        {
            // TODO uncomment below to create an instance of EmploymentType
            //instance = new EmploymentType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmploymentType
        /// </summary>
        [Fact]
        public void EmploymentTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmploymentType
            //Assert.IsType<EmploymentType>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
