/*
 * Workforce API
 *
 * Public API for the Workforce software
 *
 * The version of the OpenAPI document: v1
 * Contact: adamlonsdale@me.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Workforce.Api;
using Workforce.Model;
using Workforce.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Workforce.Test.Model
{
    /// <summary>
    ///  Class for testing Region
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Region
        //private Region instance;

        public RegionTests()
        {
            // TODO uncomment below to create an instance of Region
            //instance = new Region();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Region
        /// </summary>
        [Fact]
        public void RegionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Region
            //Assert.IsType<Region>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ShortCode'
        /// </summary>
        [Fact]
        public void ShortCodeTest()
        {
            // TODO unit test for the property 'ShortCode'
        }

    }

}
